### PR TITLE
As a renter i can see one pokemon

### PR DESCRIPTION
**Pull request by valerow-creator**
@stshayna 
Please let me know when you have a chance to go through this one

### CODE REVIEW

**Comment by stshayna** [comment]
We discussed and pulled the origin master. The show page is showing in localhost now (awesome!), just need to also display full details including owner, price and location. Thanks!

**Comment by valerow-creator** [comment]
@stshayna 
the footer is fixed

**Comment by valerow-creator** [comment]
@stshayna location and price added

**Review by DenzelBraithwaite — APPROVED** [review]
Great job Williams, looks great!

**Pull request merged**
